version: '3'

dotenv: ['.env']

tasks:

  clean:
    cmds:
      - find . -type f -name '*_string.go' -print0 | xargs -0 rm -vf 

  go-fmt:
    cmds:
      - cmd: gofumpt -l -w .
        ignore_error: true

  go-gen:
    cmds:
      - go generate ./...

  build:
    dotenv: ['.env']
    cmds:
      - task: clean
      - task: go-fmt
      - task: go-gen
      - >-
        go build
        -o bin/$PCAP_BIN_NAME
        {{if .VERBOSE}}-v -a{{end}}
        cmd/pcap.go

  dist:
    cmds:
      - task: build
        vars:
          VERBOSE: true

  docker-build:
    cmds:
      - task: clean
      - task: go-fmt
      - >-
        docker buildx build --no-cache --file=Dockerfile
        --output={{.USER_WORKING_DIR}}/bin --target=releaser {{.USER_WORKING_DIR}}
