version: '3'

dotenv: ['.env']

tasks:

  clean:
    cmds:
      - find . -type f -name '*_string.go' -print0 | xargs -0 rm -vf 

  go-gmt:
    cmds:
      - gofumpt -l -w .

  go-gen:
    cmds:
      - go generate ./...

  build:
    dotenv: ['.env']
    cmds:
      - task: clean
      - task: go-fmt
      - task: go-gen
      - >-
        go build
        -o bin/$PCAP_BIN_NAME
        {{if .VERBOSE}}-v -a{{end}}
        cmd/pcap.go

  dist:
    cmds:
      - task: build
        vars:
          VERBOSE: true
